### PR TITLE
Proguard/impl (#64)

### PR DESCRIPTION
**Pull request by jameskeith**
* wip

* proguard initial

* gradle 6.7.1 and agp 4.1.1

* gradle wrapper

* wip

* proguard

* collect consumer rules

* proguard hdl

* proguard

* proguard

* proguard location

* proguard remotecommands

* proguard config

* proguard tagmgmt

* wip

* keeppackagenames

* keeppackagenames

* keeppackagenames

* keeppackagenames

* keeppackagenames

* keeppackagenames

* keeppackagenames

* keeppackagenames

* jsonutils

* core consumer rules

* timed event proguard

### CODE REVIEW

**Review by tamayok — APPROVED** [review]
Looks good

**Comment by langerhans** [comment]
You have the following rules in every file:
```
-keepparameternames
-keeppackagenames
-renamesourcefileattribute SourceFile
-keepattributes Exceptions,InnerClasses,Signature,Deprecated,
                SourceFile,LineNumberTable,*Annotation*,EnclosingMethod
```

Are you aware that ProGuard rules a library defines affect the whole app which uses the library? IMHO having these rules in a library is a no-go as they would lead to exposing a ton of our app's code in cleartext.

**Comment by jameskeith** [comment]
Hi @langerhans - thanks for raising this with us; must have missed that part in the Proguard docs.

I'll raise a job internally to have the `consumerProguard` rules re-examind. My understanding is that we're safe to use those `-keep` statements for the initial shrinking when generating the release library's `.aar` - as some Kotlin features rely on some of the `-keep` statements above.
So it's likely a case that we remove them from the consumer files so as not to affect the resulting app's shrink process.

**Comment by langerhans** [comment]
Thank you for the quick response! There is more information about the additive nature of ProGuard configs on this page, and specifically the table in the linked section: https://developer.android.com/studio/build/shrink-code#configuration-files
I'm not an expert on the inner workings of the consumerProguard directive, but what you say sounds sensible to me.

**Pull request merged**
